import type { Product, ProductClass, StockLocation, Unit } from "./types";

type Row = [string, Unit, ProductClass, string];

// Cadastro de insumos da Fazenda São Pedro
const ROWS: Row[] = [
  ["PROFOL EXCLUSIVE", "kg", "Nutrição", ""],
  ["PROFOL PRODUTIVIDADE", "kg", "Nutrição", ""],
  ["DA CAFÉ", "L", "Nutrição", ""],
  ["STOLLER MAGNESIO", "L", "Nutrição", ""],
  ["MAP", "kg", "Nutrição", ""],
  ["OCHIMA", "L", "Óleo Mineral", "Óleo mineral"],
  ["CROP EVO", "L", "Nutrição", ""],
  ["SEMENTE BRACHIARIA", "kg", "Semente", "Semente"],
  ["P51", "L", "Nutrição", ""],
  ["STIMULATE", "L", "Nutrição", ""],
  ["HOLD", "L", "Nutrição", ""],
  ["STARPHOS", "L", "Nutrição", ""],
  ["IMPRUVER", "L", "Nutrição", ""],
  ["PROFOL BORO", "L", "Nutrição", ""],
  ["KELLUS IMUNE", "kg", "Nutrição", ""],
  ["KELLUS MANGANESE", "kg", "Nutrição", ""],
  ["MOL", "L", "Outro", ""],
  ["ADJUST SILVER", "L", "Adjuvante", "Adjuvante pulverização"],
  ["UP BOR", "L", "Nutrição", ""],
  ["OMITE", "L", "Acaricida", "Propargito"],
  ["PERENION", "L", "Fungicida/Bactericida", "Fluxapiroxade + Oxicloreto de cobre"],
  ["TEBURAZ", "L", "Fungicida", "Azoxistrobina + Tebuconazol"],
  ["MIRAVIS DUO", "L", "Fungicida", "Difenoconazol + Pidiflumetofem"],
  ["PRIORI XTRA", "L", "Fungicida", "Azoxistrobina + Ciproconazol"],
  ["PRIORI TOP", "L", "Fungicida", "Azoxistrobina + Difenoconazol"],
  ["COMET", "L", "Fungicida", "Piraclostrobina"],
  ["ALTO 100", "L", "Fungicida", "Ciproconazol"],
  ["EPINGLE", "L", "Inseticida", "Piriproxifem"],
  ["GOEMON", "L", "Inseticida", "Ciclaniliprole"],
  ["CURYOM", "L", "Inseticida", "Profenofós + Lufenurom"],
  ["VERANGO PRIME", "L", "Nematicida/Fungicida", "Fluopiram"],
  ["VIVANTHA", "kg", "Inseticida", "Tiametoxam"],
  ["JOINER", "L", "Inseticida/Acaricida", "Isocicloseram"],
  ["INFLUX", "kg", "Inseticida", "Benzoato de emamectina + Lufenurom"],
  ["YAMATO", "L", "Herbicida", "Piroxasulfona"],
  ["ZAPP QI", "L", "Herbicida", "Glifosato sal de potássio"],
  ["AURORA", "L", "Herbicida", "Carfentrazona-etílica"],
  ["FRENO", "L", "Herbicida", "Cletodim"],
  ["JOYA", "L", "Herbicida", "Flumioxazina"],
  ["JOINT ULTRA", "L", "Óleo Mineral", "Óleo mineral"],
  ["HEAT", "kg", "Herbicida", "Saflufenacil"],
  ["GOAL", "L", "Herbicida", "Oxifluorfem"],
  ["BOSCALID", "kg", "Fungicida", "Boscalida"],
  ["CONCORD", "L", "Nutrição", ""],
  ["NICOMO DRY", "kg", "Nutrição", ""],
  ["ALION", "L", "Outro", ""],
  ["ADJUST HERB", "L", "Adjuvante", "Adjuvante herbicida"],
  ["TRITTER", "kg", "Outro", ""],
  ["CONVICTO", "L", "Outro", ""],
  ["PODERUS", "L", "Outro", ""],
  ["BIO TRIO", "L", "Outro", ""],
  ["HELPER DESSEK", "L", "Adjuvante", "Adjuvante herbicida"],
  ["20-05-20", "kg", "Nutrição", "NPK 20-05-20"],
  ["CALCÁRIO", "kg", "Nutrição", ""],
  ["34-00-00", "kg", "Nutrição", "NPK 34-00-00"],
  ["PRODUCOTE", "kg", "Nutrição", ""],
  ["MAGBOR", "kg", "Nutrição", ""],
  ["YORIN", "kg", "Nutrição", ""],
  ["SUPERA", "L", "Outro", ""],
  ["CANTUS", "kg", "Outro", ""],
  ["CORDIAL", "L", "Outro", ""],
  ["VERTIMEC 84", "L", "Acaricida", ""],
  ["VOLIAN TARGO", "L", "Inseticida", ""],
  ["CARTARYS", "kg", "Inseticida", ""],
  ["OBERON", "L", "Acaricida", ""],
  ["POLO", "L", "Inseticida", ""],
  ["LOKOMOTIVE", "L", "Outro", ""],
  ["CAPATAZ", "L", "Inseticida", "Clorpirifós"],
  ["KLORPAN", "L", "Inseticida", "Clorpirifós"],
  ["YARA VITA CAFÉ", "L", "Nutrição", ""],
  ["OPERA", "L", "Fungicida", ""],
  ["ABADAY", "L", "Outro", ""],
  ["GLIDER", "L", "Outro", ""],
  ["CHARRUA", "L", "Outro", ""],
  ["SEVARE", "L", "Outro", ""],
  ["NANO CARBONO", "L", "Nutrição", ""],
  ["ORGANO CARBONO", "L", "Nutrição", ""],
  ["TALISMAN", "L", "Outro", ""],
  ["GLUCARE", "L", "Outro", ""],
  ["DECORUM", "L", "Outro", ""],
  ["ACTIMAX PHOS", "L", "Nutrição", ""],
  ["PHISIOMIX PRO", "L", "Nutrição", ""],
  ["RAINZEB", "L", "Fungicida", ""],
  ["VERSALIS", "L", "Outro", ""],
  ["ADUBO PLANTIO MILHO", "kg", "Nutrição", "NPK 06-30-05"],
  ["CELLERATE", "L", "Nutrição", ""],
  ["IHAROL GOLD", "L", "Óleo Mineral", "Óleo mineral"],
  ["CARPIDORA", "kg", "Outro", ""],
  ["STOLLER MANGANES", "L", "Nutrição", ""],
  ["STOLLER MOVER", "L", "Nutrição", ""],
  ["STOLLER FERRO", "L", "Nutrição", ""],
  ["STOLLER COBRE", "L", "Nutrição", ""],
  ["RE-LEAF", "L", "Nutrição", ""],
  ["TARGA MAX", "L", "Herbicida", ""],
  ["SPIRIT", "L", "Outro", ""],
  ["EXION VIDA", "L", "Nutrição", ""],
  ["DUAL GOLD", "L", "Herbicida Seletivo", "S-metolacloro + Nafta de petróleo"],
  ["PANZER", "kg", "Herbicida", "Clorimurom"],
  ["KEEP GREEN", "L", "Outro", ""],
  ["AFIADO", "L", "Acaricida", "Acetamiprido + Bifentrina"],
  ["SONDA", "L", "Herbicida", "Terbutilazina"],
  ["CLORIMUROM MAX", "kg", "Herbicida", "Clorimurom"],
  ["OFF ROAD", "L", "Outro", ""],
  ["KRYPTO", "L", "Outro", ""],
  ["FLUID TURBO", "L", "Outro", ""],
  ["AUDAZ", "L", "Outro", ""],
  ["ORKESTRA", "L", "Fungicida", ""],
  ["CLORPIRI 480", "L", "Inseticida", "Clorpirifós"],
  ["SUMYZIN 500", "L", "Outro", ""],
  ["BIVACK", "L", "Herbicida", "Carfentrazona-etílica"],
  ["POQUER", "L", "Herbicida", "Cletodim"],
  ["CLIPER", "kg", "Herbicida", "Clorimurom"],
  ["HAMPTON", "L", "Herbicida", "Carfentrazona-etílica"],
  ["GRASIDIM", "L", "Herbicida", "Cletodim"],
  ["ACTARA 250WG", "kg", "Inseticida", "Tiametoxam"],
  ["SUPPORT 500", "L", "Fungicida", "Tiofanato metílico"],
  ["SULFATO DE AMÔNIA", "kg", "Adubo", "20-00-00"],
  ["ÁCIDO BÓRICO", "kg", "Adubo", ""],
  ["CERCOBIN 875", "kg", "Fungicida", ""],
  ["FLUMYZIN", "L", "Herbicida", "Flumioxazina 500"],
];

export const SEED_PRODUCTS: Product[] = ROWS.map((r, i) => ({
  id: `P${String(i + 1).padStart(3, "0")}`,
  name: r[0],
  unit: r[1],
  productClass: r[2],
  activeIngredient: r[3],
}));

/** Locais de estoque/talhões já usados historicamente nas movimentações, + novos exemplos */
const LOCATION_NAMES = [
  "ESTOQUE",
  "BARRACÃO",
  "PORTEIRA",
  "OURO PRETO",
  "SECADOR",
  "TULHA",
  "SP-1",
  "SP-2",
  "SP-3",
  "SP-4",
  "SP-5",
  "SP-6 CIMA",
  "SP-6 BAIXO",
  "SP-7 CIMA",
  "SP-7 BAIXO",
  "SP-9",
  "SP-22",
  "SP-23",
  "SP-24",
  "SP-25",
  "SP-25 BAIXO",
  "MR-1 CIMA",
  "MR-1 BAIXO",
  "MR-2",
  "OP-1",
  "OP-2 CIMA",
  "OP-2 BAIXO",
  "SB-1",
  "SB-2",
  "FAZENDA SANTUÁRIO",
  "MILHO 25-26",
  "REVENDA",
  "Fazenda São Pedro",
  "Almoxarifado",
  "Galpão 01",
];

export const SEED_STOCK_LOCATIONS: StockLocation[] = LOCATION_NAMES.map((name, i) => ({
  id: `LOC${String(i + 1).padStart(3, "0")}`,
  name,
}));
